"""add_subject_initialization_columns

Revision ID: 3b9c95b4edf0
Revises: ac9926149e2c
Create Date: 2026-07-24 11:32:33.921172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9c95b4edf0'
down_revision: Union[str, Sequence[str], None] = 'ac9926149e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('initial_conducted', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('initial_attended', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'initial_attended')
    op.drop_column('subjects', 'initial_conducted')
    # ### end Alembic commands ###
