"""add subject track_attendance column

Revision ID: 5315fdf5216a
Revises: cf043b9189f2
Create Date: 2026-08-03 03:05:20.397543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5315fdf5216a'
down_revision: Union[str, Sequence[str], None] = 'cf043b9189f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('track_attendance', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'track_attendance')
    # ### end Alembic commands ###
