"""add_working_days_and_overrides

Revision ID: 6adfcd27a879
Revises: 665c07801550
Create Date: 2026-07-18 00:47:02.094764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adfcd27a879'
down_revision: Union[str, Sequence[str], None] = '665c07801550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('timetable_day_override', sa.Integer(), nullable=True))
    op.add_column('semesters', sa.Column('working_days', sa.String(), server_default='0,1,2,3,4', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semesters', 'working_days')
    op.drop_column('calendar_events', 'timetable_day_override')
    # ### end Alembic commands ###
