"""add active dates and room columns

Revision ID: ac78f7b8c03e
Revises: 5315fdf5216a
Create Date: 2026-08-03 12:08:43.350859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac78f7b8c03e'
down_revision: Union[str, Sequence[str], None] = '5315fdf5216a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_occurrences', sa.Column('room', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('active_from', sa.Date(), nullable=True))
    op.add_column('subjects', sa.Column('active_until', sa.Date(), nullable=True))
    op.add_column('timetable_slots', sa.Column('room', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable_slots', 'room')
    op.drop_column('subjects', 'active_until')
    op.drop_column('subjects', 'active_from')
    op.drop_column('lecture_occurrences', 'room')
    # ### end Alembic commands ###
