"""add_refined_calendar_columns

Revision ID: ac9926149e2c
Revises: fea8c35ceea9
Create Date: 2026-07-21 01:38:33.740500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9926149e2c'
down_revision: Union[str, Sequence[str], None] = 'fea8c35ceea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('title', sa.String(), nullable=True))
    op.add_column('calendar_events', sa.Column('category', sa.String(), nullable=True))
    op.add_column('calendar_events', sa.Column('schedule_effect', sa.String(), nullable=True))
    op.add_column('calendar_events', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'end_date')
    op.drop_column('calendar_events', 'schedule_effect')
    op.drop_column('calendar_events', 'category')
    op.drop_column('calendar_events', 'title')
    # ### end Alembic commands ###
