"""add_semester_is_active_column

Revision ID: ccbc49bb3515
Revises: adffda6d1aa3
Create Date: 2026-07-24 11:54:49.579063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbc49bb3515'
down_revision: Union[str, Sequence[str], None] = 'adffda6d1aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semesters', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semesters', 'is_active')
    # ### end Alembic commands ###
