"""add_subject_earned_lost_units

Revision ID: cf043b9189f2
Revises: 2ede2f0777c3
Create Date: 2026-07-31 12:19:40.627386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf043b9189f2'
down_revision: Union[str, Sequence[str], None] = '2ede2f0777c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('subjects', sa.Column('units_earned_per_class', sa.Integer(), server_default='1', nullable=False))
    op.add_column('subjects', sa.Column('units_lost_per_class', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'units_lost_per_class')
    op.drop_column('subjects', 'units_earned_per_class')
    # ### end Alembic commands ###
