"""add_exam_day_columns

Revision ID: fea8c35ceea9
Revises: 6adfcd27a879
Create Date: 2026-07-18 01:10:48.355410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea8c35ceea9'
down_revision: Union[str, Sequence[str], None] = '6adfcd27a879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('calendar_events', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('calendar_events', sa.Column('end_time', sa.Time(), nullable=True))
    op.create_foreign_key(None, 'calendar_events', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'end_time')
    op.drop_column('calendar_events', 'start_time')
    op.drop_column('calendar_events', 'subject_id')
    # ### end Alembic commands ###
