import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { GraduationCap, ChevronRight, ChevronLeft, Sparkles, Calendar, Compass, CheckSquare } from "lucide-react";

interface IntroSlide {
  title: string;
  description: string;
  icon: React.ComponentType<any>;
  details: string[];
}

const Welcome: React.FC = () => {
  const navigate = useNavigate();
  const [currentSlide, setCurrentSlide] = useState(0);

  const slides: IntroSlide[] = [
    {
      title: "Welcome to AttendWise",
      description: "Plan your attendance terms smarter. Let's walk through the core planning tools before configuring your active semester timeline.",
      icon: GraduationCap,
      details: [
        "Track term metrics, safe bunk budgets, and target thresholds.",
        "Auto-generate calendar occurrences based on weekly timetables.",
        "Interactive leave assistant powered by Gemini AI."
      ]
    },
    {
      title: "What AttendWise Helps You Do",
      description: "Manage your courses, plan absences, and prevent attendance drops without manual spreadsheet logging.",
      icon: CheckSquare,
      details: [
        "Monitor overall and subject-specific attendance percentages.",
        "Identify courses nearing or dropping below critical requirements.",
        "Track exact counts of conducted, attended, and cancelled lectures."
      ]
    },
    {
      title: "How Attendance Tracking Works",
      description: "Logging conduct is extremely straightforward. Seed your historical records with a few simple clicks.",
      icon: Calendar,
      details: [
        "Log conducted classes daily using today's schedule checklist.",
        "Mark lectures as Present, Absent, or Cancelled.",
        "Access historical occurrences inside our fully featured monthly calendar."
      ]
    },
    {
      title: "Deterministic Absences simulation",
      description: "Our planner projects stats before you skip a class, verifying exactly how absences affect your future standing.",
      icon: Compass,
      details: [
        "Select future leave dates on the interactive timeline.",
        "Compare current percentages against simulated projections.",
        "View warning alerts before making decision bunks."
      ]
    },
    {
      title: "How the AI Leave Assistant Helps",
      description: "Consult the built-in AI Assistant in natural language. It queries active semester timelines deterministically.",
      icon: Sparkles,
      details: [
        "Ask queries like: 'Can I bunk science tomorrow?' or 'Suggest leaves next week.'",
        "Interact with persistent, date-grouped chat records.",
        "Review clean, explainable forecast outputs generated by the planner engine."
      ]
    }
  ];

  const handleNext = () => {
    if (currentSlide < slides.length - 1) {
      setCurrentSlide(currentSlide + 1);
    } else {
      handleFinishOnboarding();
    }
  };

  const handleBack = () => {
    if (currentSlide > 0) {
      setCurrentSlide(currentSlide - 1);
    }
  };

  const handleFinishOnboarding = () => {
    localStorage.setItem("wizard_setup_completed", "false"); // Ensure setup wizard runs next
    navigate("/setup?mode=new");
  };

  const activeSlide = slides[currentSlide];
  const IconComponent = activeSlide.icon;

  return (
    <div className="min-h-screen bg-background text-foreground antialiased selection:bg-accent selection:text-foreground flex flex-col justify-center items-center px-6 py-12">
      
      {/* Background radial highlight */}
      <div className="absolute top-1/4 h-72 w-72 rounded-full bg-primary/5 blur-[120px] pointer-events-none" />

      {/* Main card */}
      <div className="max-w-md w-full border border-border bg-card rounded-2xl p-6 sm:p-8 shadow-xl space-y-6 relative overflow-hidden animate-scale-in">
        
        {/* Top Progress Indicators */}
        <div className="flex items-center justify-between border-b border-border/60 pb-4">
          <div className="flex items-center space-x-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg border border-border bg-background shadow-sm">
              <GraduationCap className="h-4 w-4 text-foreground" />
            </div>
            <span className="text-xs font-bold tracking-tight text-foreground">Guide Tour</span>
          </div>

          <span className="text-[10px] text-muted-foreground font-semibold">
            Step {currentSlide + 1} of {slides.length}
          </span>
        </div>

        {/* Slide Progress bar */}
        <div className="w-full bg-muted h-1 rounded-full overflow-hidden">
          <div 
            className="bg-primary h-full transition-all duration-300"
            style={{ width: `${((currentSlide + 1) / slides.length) * 100}%` }}
          />
        </div>

        {/* Slide Content */}
        <div className="space-y-5 py-2 animate-scale-in" key={currentSlide}>
          <div className="flex items-center space-x-3">
            <div className="h-9 w-9 rounded-xl bg-primary/10 border border-primary/15 flex items-center justify-center text-primary shrink-0">
              <IconComponent className="h-5 w-5" />
            </div>
            <h2 className="text-base font-bold tracking-tight text-foreground">{activeSlide.title}</h2>
          </div>

          <p className="text-xs leading-relaxed text-muted-foreground">
            {activeSlide.description}
          </p>

          <ul className="space-y-2.5 pt-2">
            {activeSlide.details.map((detail, idx) => (
              <li key={idx} className="flex items-start space-x-2 text-xs text-foreground">
                <span className="h-1.5 w-1.5 rounded-full bg-primary shrink-0 mt-1.5" />
                <span className="leading-relaxed">{detail}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between pt-4 border-t border-border/60">
          <button
            onClick={handleFinishOnboarding}
            className="text-xs font-semibold text-muted-foreground hover:text-foreground cursor-pointer transition-colors"
          >
            Skip Guide
          </button>

          <div className="flex items-center space-x-2">
            {currentSlide > 0 && (
              <button
                onClick={handleBack}
                className="flex items-center justify-center h-8 w-8 rounded-lg border border-border bg-background hover:bg-muted text-muted-foreground hover:text-foreground cursor-pointer transition-all"
              >
                <ChevronLeft className="h-4 w-4" />
              </button>
            )}

            <button
              onClick={handleNext}
              className="rounded-lg bg-primary py-1.5 px-4 text-xs font-bold text-primary-foreground hover:bg-neutral-800 transition-all cursor-pointer flex items-center space-x-0.5"
            >
              <span>{currentSlide === slides.length - 1 ? "Finish" : "Next"}</span>
              <ChevronRight className="h-4 w-4" />
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};

export default Welcome;
